Update scan-with-endorlabs.yml

diff --git a/.github/workflows/scan-with-endorlabs.yml b/.github/workflows/scan-with-endorlabs.yml
--- a/.github/workflows/scan-with-endorlabs.yml
+++ b/.github/workflows/scan-with-endorlabs.yml
@@ -89,21 +89,27 @@ jobs:
             exit 2
           fi
 
-      - id: endorlabs-clone
-        name: clone ${{ inputs.git-url }}
-        shell: bash
-        env:
-          CLONE_URL: "https://${{secrets.REPO_PAT}}${{ inputs.git-url }}"
-        run: |
-          if (git clone "${CLONE_URL}" "project"); then
-            >&2 echo "Cloned '${CLONE_URL}' successfully using bare git"
-          else
-            >&2 echo "Failed to clone '${CLONE_URL}' with bare git, trying gh"
-            if ! (gh repo clone "${CLONE_URL}" "project"); then
-              echo "::error::unable to clone '${CLONE_URL}' with any supported method"
-              exit 1
-            fi
-          fi
+      # - id: endorlabs-clone
+      #   name: clone ${{ inputs.git-url }}
+      #   shell: bash
+      #   env:
+      #     CLONE_URL: "https://${{secrets.REPO_PAT}}${{ inputs.git-url }}"
+      #   run: |
+      #     if (git clone "${CLONE_URL}" "project"); then
+      #       >&2 echo "Cloned '${CLONE_URL}' successfully using bare git"
+      #     else
+      #       >&2 echo "Failed to clone '${CLONE_URL}' with bare git, trying gh"
+      #       if ! (gh repo clone "${CLONE_URL}" "project"); then
+      #         echo "::error::unable to clone '${CLONE_URL}' with any supported method"
+      #         exit 1
+      #       fi
+      #     fi
+
+      - id: endorlabs-checkout
+        uses: actions/checkout@v3
+        with:
+          repository: ${{ inputs.git-url }}
+          token: ${{ secrets.REPO_PAT }}
         
       - id: endorlabs-setup
         name: install endorlabs client
@@ -119,8 +125,8 @@ jobs:
             echo "::endgroup::"
           fi
           mkdir -p "${ENDOR_HOME}"
-          curl -o "${ENDOR_HOME}/endorctl" ${ENDOR_API}/download/v1.6.346/endorctl_${ENDOR_OS}_${ENDOR_ARCH}
-          echo "dbef637e7f068473f0401fd1954e746a706f657e1fedc166aff370be93ece87a  endorctl" | sha256sum -c || exit 1
+          curl -o "${ENDOR_HOME}/endorctl" ${ENDOR_API}/download/latest/endorctl_${ENDOR_OS}_${ENDOR_ARCH}
+          echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_${ENDOR_OS}_${ENDOR_ARCH})  ${ENDOR_HOME}/endorctl" | sha256sum -c || exit 1
           chmod +x "${ENDOR_HOME}/endorctl"
           if [[ -n "$ENDORLABS_API_AUTH" ]]; then
             echo "::notice::Disabling GitHub Actions OIDC auth for Endor Labs, using API key auth instead"
